Demand components
BayAreaMetro/tm2py pull request #60
Opened 2022-04-28 16:29 UTC by inrokevin

## Adding main non-resident demand components
Closes #59
Closes #34 
Closes #33

## Testing plan
 - [X] Code for this PR is covered in tests, basic model run test added which executes these steps together with highway (transit to be added when branches are merged together)
 - [X] Code passes all existing tests
 - [X] Code linted

2022-05-03 20:47 UTC, e-lo requested changes
Min needs to be addressed: add tests (there are none!) and missing docstrings
Preferable (although could be a refactor later...@lmz..) is to 
a. pull out common functions to be referenced by many processes
b. parameterize in parameters, not in magic numbers

2022-05-03 20:47 UTC, e-lo commented on tm2py/emme/matrix.py
> +    def __init__(
docstrings for __init__ args go here. 
docstrings for instance attributes go in class-level docstrings

2022-05-03 20:47 UTC, e-lo commented on tm2py/emme/matrix.py
> +            toll_factor: Optional factor to apply to the tolls
more description please - this is multiplied by the tolls? what is an example use case?

2022-05-03 20:47 UTC, e-lo commented on tm2py/emme/matrix.py
> +            A numpy array with the calculated exp(util) result.
add dimensions/units for the numpy array

2022-05-03 20:47 UTC, e-lo commented on tm2py/emme/matrix.py
> +    def mask_non_available(
This seems like it should be a "general step" for every mode - why is it special for tolls?
2. Shouldn't this be reading in and returning a masked skim?
3. Where are probabilities for tolls zero-ed out? It seems like it should be in same step.

2022-05-03 20:47 UTC, e-lo commented on tm2py/emme/matrix.py
> +class TollChoiceCalculator:
why is this in emme/matrix? Does it use Emme?

2022-05-03 20:47 UTC, e-lo commented on tm2py/emme/matrix.py
> +class TollChoiceCalculator:
i.e. why isn't this a model component which could then reference some general matrix/choice model language/tools

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
> +    production: float
add requirements (i.e. between 0-1, sum of both are 1)

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
> +    time_period: str
add requirements

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
> +    zone_index: int
add requirement

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
> +    factor: float
add requirement.

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
> +    """Mapping of gateway (zone ordering ID) to factor value"""
what the heck is a "factor value"? :-)

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
>      reference_start_year: str
add requirement
(and why a string not an int?)

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
>      reference_end_year: str
ditto

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
>      result_class_name: str
add requirement, should be one of....

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
>      src_group_name: str
add requirement, should be one of...

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
> +        src_group_name: name used for the class group in the input columns
what is the meaning of "class group"? (example would help)

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
> +            HighwayClassDemandConfig name(s)
Add example

2022-05-03 20:47 UTC, e-lo commented on tm2py/config.py
> +        access_modes: list of names used for the access modes in the input
don't see this there?

2022-05-03 20:47 UTC, e-lo commented on tests/test_union_city.py
There aren't any tests for any of these submodules.

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +    from tm2py.controller import RunController
oh fancy! i like this !(assuming it works)

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +        """Build the airport trip matrices"""
add docstring about steps it is doing here

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +    def _interpolate(self, aggr_demand: pd.DataFrame) -> pd.DataFrame:
This should be a common element shared for components.

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +    def _interpolate(self, aggr_demand: pd.DataFrame) -> pd.DataFrame:
[ and have a unit-test ]

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +        start_year = int(self._start_year)
these should be args

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +    def _export_result(self, demand: pd.DataFrame):
probably also a common element

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +        for year in [self._start_year, self._end_year]:
itertools.product()?

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +    def _load_demand(self) -> pd.DataFrame:
is there anything special here? if so, suggest _load_air_demand() or similar.

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +        scale = float(int(year) - start_year) / (end_year - start_year)
scale demand seems like it should be a common function...

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +_land_use_aggregation = {
a param?

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +        link_trips["vsmtrk_prod"] = (
param?

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +        garage_trips["smltrk_prod"] = (
param?

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +        Uses 1/3 * AM + 2/3 * MD, sources skims from generated OMX files
make the blending factors a param?

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +        """Blend AM and MD truck times for distribution calculations.
make time periods a param?

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +    def _time_of_day(
this function name should  be an action, not a noun - ex: `_split_by_time_period

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +        self, daily_demand: Dict[str, Dict[str, NumpyArray]]
demand, factors should be params?

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +    def _time_of_day(
Does this happen other places? seems like a common method which could be specified in one place.

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/commercial.py
> +    def _toll_choice(
why is this here but here is another one in emme/matrix?

If this is common function, should pull out.

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/household.py
> +            "set PATH=%CD%\\CTRAMP\runtime;C:\\Windows\\System32;%JAVA_PATH%\bin;"
make paths safe

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/household.py
> +    """Run household resident model"""
document more

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/internal_external.py
> +        """docstring for component run"""
add docstring

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/internal_external.py
> +    def _growth_forecast(self, demand: Dict[str, NumpyArray]) -> Dict[str, NumpyArray]:
seems like a good common function?

2022-05-03 20:47 UTC, e-lo commented on tm2py/components/demand/internal_external.py
> +    def _toll_choice(
ditto from other

2022-05-10 15:36 UTC, e-lo commented on tm2py/components/demand/air_passenger.py
> +        """Build the airport trip matrices"""
fixed

2022-07-14 20:43 UTC, lmz commented
Is this pull request still in progress or can it be merged?

2022-07-19 17:23 UTC, lmz commented
Hello - I'm taking a deeper look at this code and testing it and I do have some thoughts/questions

1. I'd like to make logging not require a context; I find it cumbersome and adds indent clutter, which makes logging feel like a big deal
2. I don't think it's necessary to include timestamp as an option in logging. Let's just include timestamps.
3. I don't understand the `log_on_error_file_path`?  What is this file?
4. Likewise, what's the `LogCache` for?

I'm making the changes for 1 and 2 but would appreciate clarification on 3 and 4.  Thank you!

2022-07-22 17:01 UTC, lmz commented
Hi @inrokevin @e-lo (@AntoineGrapperon in case @inrokevin is not available) -
Just pinging on my two questions above: What is LogCache and log_on_error_file_path for?
I don't want the logging system to be over-complicated, and I think two log files seem like they should be sufficient; it seems like error messages should be in both of the other two logs so why the need for a 3rd, and why the need for a LogCache system?

2022-07-22 17:14 UTC, e-lo commented
As I think I've said before, I agree with @lmz that we shouldn't have to use a context - see #83 for the defined problem.

Since I am not really familiar with how @inrokevin implemented the context and what the referenced `LogCache` and `log_on_error_file_path` are for because I was hoping we would fix it wholesale. 

Do you think we need to:
(1) *fix* the logging with context in this PR? or 
(2) can we save this as an issue for now and not have it blocking the merge?

My preference in order to get things done now is 2...but you're the boss!

2022-07-22 19:57 UTC, lmz commented
Got it. 

I opened #87 regarding the `LogCache` and `log_on_error_file_path`.  Although I just noted the description [in the doc here]( https://bayareametro.github.io/tm2py/demand_components/contributing/development/#viewing-logging) which refers to the `log_on_error_file_path` as pointing to the "Catch-all Log".  So from this standpoint, it defers from the detailed log or debug log in that it has trace as well?  But it also doesn't seem to always trigger?  In any case, I'm ok with punting on issue #87 for now.

 #83 bothers me too much so I checked in a fix (not 100% sure it's complete given my confusion around #87).

2022-09-11 21:39 UTC, i-am-sijia commented
Passing tests:

- tests/test_air_access.py
- tests/test_trucks.py
- tests/test_externals.py

Example union city data: [UnionCity.zip](https://github.com/BayAreaMetro/tm2py/blob/demand_components/examples/UnionCity.zip)

2022-09-14 17:01 UTC, e-lo commented
@i-am-sijia it looks like somewhere the github runner is assigning the wrong value to `controller.run_dir`.  Locally I get: `Users/elizabeth/Documents/urbanlabs/working/tm2py/examples/UnionCity`
GH Actions seems to be getting a double `tm2py` 

Suggest troublshooting the below conftest.py fixture to see if it needs to be more resilient:

```python
@pytest.fixture(scope="session")
def root_dir():
    """Root tm2py directory."""
    return Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
```

2022-09-15 19:28 UTC, i-am-sijia commented
@e-lo I don't think the path in GH Actions is wrong. Looking at the log, it was able to find other files with the additional `tm2py` in path:

![image](https://user-images.githubusercontent.com/28812722/190491831-0a0dcd79-bd26-4f3f-a7e9-39e9599933d8.png)

I think the problem is that this log file is not created:
![image](https://user-images.githubusercontent.com/28812722/190492161-412b8d25-716a-4057-b515-cc68caee58aa.png)

2022-09-15 21:25 UTC, i-am-sijia commented
@e-lo I think I found the reason... `'/home/runner/work/tm2py/tm2py/examples/UnionCity/'` folder does not exist because some test does not run the get example data step.

2022-09-19 13:48 UTC, i-am-sijia commented
Passed all local tests. GH Actions are also passed. Ready to merge into Develop.

2022-09-19 13:48 UTC, merged